# Learn more about configuring your extension at 
# https://shopify.dev/docs/apps/app-extensions/configuration

api_version = "2026-01"
name = "promo-action"

uid = "aa547cf4-9a0e-d512-e8ae-3ee421ff0a10dd6ee30b"

type = "ui_extension"

[[targeting]]
module = "./src/ActionExtension.jsx"
target = "admin.discount-code-basic.action.render"
